# Generated by Django 4.0.5 on 2022-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_archive', models.BooleanField(default=False)),
            ],
        ),
    ]
