# Generated by Django 4.0.5 on 2022-08-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Book',
        ),
    ]
