# Generated by Django 4.0.5 on 2022-08-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_cart_book_price_book_quantity_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='book',
            new_name='product',
        ),
    ]
